services:
#    front.example:
#        class: FrontBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    applicant_bag:
        class: FrontBundle\Service\ApplicantBag
        arguments: ['@session']
