applicant:
    resource: "@ApplicantBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /securite/deconnexion

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
