front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

candidate:
    resource: "@CandidateBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /securite/deconnexion

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
