security:
    encoders:
        UserBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            provider: db_provider
            anonymous: ~
            form_login:
                check_path: security_user_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: security_index
                login_path: security_user_login
            logout:
                path:   /securite/deconnexion
                target: /securite/connexion
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                secure:   true

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/securite/connexion,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/securite/utilisateurs,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,                       roles: ROLE_USER }
